[build-system]
requires = ["aiohttp >=3.8.3","pytest-asyncio==0.19.0"]

[project]
name = "pyAnduro"
authors = [
    {name = "Merca Ovnerud", email = "merca.ovnerud@proton.me"},
]
readme = "README.md"
license = ["LICENSE"]

requires-python = ">=3.9"
dynamic = ["version", "description"]
