[build-system]
requires = ["aiohttp >=3.8.3","pytest-asyncio==0.19.0"]

[project]
name = "pyAnduro"
authors = [
    {name = "Merca Ovnerud", email = "merca.ovnerud@proton.me"},
]
readme = "README.rst"
classifiers = [
    "License:: MIT License",
]
requires-python = ">=3.9"
dynamic = ["version", "description"]