name: ⌨ check spelling
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1.12.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
