name: Python package

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Black
        uses: dciborow/pyaction@0.2.0
        with:
          black: true
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pytest
        uses: dciborow/pyaction@0.2.0
        with:
          testing: true
