name: 💠 Python lint

on:
  push:
    branches:
      - current
      - next
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: ⚫ black
        uses: microsoft/action-python@0.2.0
        with:
          black: true
          workdir: .
      - name: 8️⃣ flake8
        uses: microsoft/action-python@0.2.0
        with:
          flake8: true
          workdir: .
      - name: 🔰 pylint
        uses: microsoft/action-python@0.2.0
        with:
          pylint: true
          workdir: .
